# Generated by Django 6.0.6 on 2026-07-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل صفحه خدمت')),
                ('tags', models.CharField(help_text='با ویرگول جدا کنید. مثلاً: سئو, محتوا, لینک سازی', max_length=500, verbose_name='تگ\u200cها')),
                ('featured', models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سکشن صفحه خدمات',
                'verbose_name_plural': 'سکشن صفحه خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceCustomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آیتم')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (میلیون تومان)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'آیتم سفارشی',
                'verbose_name_plural': 'آیتم\u200cهای سفارشی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'خروجی',
                'verbose_name_plural': 'خروجی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('starter', 'استارتر'), ('pro', 'پیشرفته'), ('enterprise', 'اختصاصی')], max_length=20, verbose_name='نوع پلن')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('price', models.CharField(help_text='مثلاً ۱۲ یا از ۵۰', max_length=50, verbose_name='قیمت')),
                ('old_price', models.CharField(blank=True, max_length=50, verbose_name='قیمت قبل از تخفیف')),
                ('discount_label', models.CharField(blank=True, help_text='مثلاً ۲۰٪ تخفیف', max_length=50, verbose_name='برچسب تخفیف')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پلن پیشنهادی؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویژگی')),
                ('included', models.BooleanField(default=True, verbose_name='شامل میشه؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.serviceplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مرحله')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مراحل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='مثلاً +۸۰ یا ۹۷٪', max_length=50, verbose_name='عدد')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='نام')),
                ('author_role', models.CharField(max_length=200, verbose_name='نقش و شرکت')),
                ('author_image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='یک ایموجی. مثلاً ⚡', max_length=10, verbose_name='آیکون')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_us', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزایا',
                'ordering': ['order'],
            },
        ),
    ]
