# Generated by Django 6.0.6 on 2026-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetestimonial',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
