# Generated by Django 6.0.5 on 2026-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('second_title', models.CharField(max_length=200, verbose_name='عنوان دوم')),
                ('text', models.TextField(verbose_name='متن معرفی')),
            ],
        ),
    ]
