# Generated by Django 6.0.6 on 2026-07-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='گزینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بودجه',
                'verbose_name_plural': 'بودجه ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_title', models.CharField(help_text='مثال: مشهد', max_length=100, verbose_name='عنوان دفتر')),
                ('office_address', models.TextField(verbose_name='آدرس دفتر')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('working_hours', models.CharField(max_length=100, verbose_name='ساعت کاری')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'هیروسکشن صفحه تماس',
                'verbose_name_plural': 'هیروسکشن صفحه تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت')),
                ('project_type', models.CharField(max_length=100, verbose_name='نوع پروژه')),
                ('budget', models.CharField(max_length=100, verbose_name='بودجه')),
                ('start_time', models.CharField(max_length=100, verbose_name='زمان شروع پروژه')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات پروژه')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('seen', 'مشاهده شده')], default='new', max_length=10, verbose_name='وضعیت')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'فرم تماس',
                'verbose_name_plural': 'فرم های تماس',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='گزینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'نوع پروژه',
                'verbose_name_plural': 'انواع پروژه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StartTimeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='گزینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'زمان شروع',
                'verbose_name_plural': 'زمان های شروع',
                'ordering': ['order'],
            },
        ),
    ]
