# Generated by Django 6.0.6 on 2026-07-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email_career',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل فرصت\u200cهای شغلی'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_press',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل رسانه'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_project',
            field=models.EmailField(blank=True, help_text='مثال: project@example.com', max_length=254, verbose_name='ایمیل پروژه\u200cهای جدید'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tagline',
            field=models.CharField(blank=True, help_text='یک جمله کوتاه در ستون تماس نمایش داده می\u200cشود', max_length=200, verbose_name='جمله کوتاه / شعار'),
        ),
    ]
