# Generated by Django 6.0.6 on 2026-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_description', models.TextField(verbose_name='توضیحات سایت')),
                ('footer_description', models.TextField(verbose_name='توضیحات فوتر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('established_year', models.CharField(max_length=10, verbose_name='سال تاسیس')),
                ('status', models.CharField(default='آماده همکاری', max_length=50, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثلا LI یا IG', max_length=10, verbose_name='برچست')),
                ('url', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
    ]
