# Generated by Django 6.0.6 on 2026-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default='', help_text='مثلا اینستاگرام', max_length=50, verbose_name='نام کامل'),
            preserve_default=False,
        ),
    ]
