# Generated by Django 6.0.6 on 2026-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sociallink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'هیروسکشن صفحه درباره ما',
                'verbose_name_plural': 'هیروسکشن صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='AboutPre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='ساب تایتل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('button_url', models.CharField(max_length=200, verbose_name='لینک دکمه')),
            ],
            options={
                'verbose_name': 'سکشن پریفوتر درباه ما',
                'verbose_name_plural': 'سکشن پریفوتر درباره ما',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='مثلا +70', max_length=50, verbose_name='عدد')),
                ('label', models.CharField(max_length=100, verbose_name='برچست')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات کوتاه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'امار و ارقام',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات ')),
            ],
            options={
                'verbose_name': 'داستان ما',
                'verbose_name_plural': 'داستان ما',
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'ارزش',
                'verbose_name_plural': 'ارزش ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role', models.TextField(verbose_name='نقش')),
                ('bio', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='team/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order'],
            },
        ),
    ]
