# Generated by Django 6.0.6 on 2026-07-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutpagehero_aboutpre_aboutstat_aboutstory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('client_website', models.URLField(verbose_name='آدرس سایت مشتری')),
                ('slug', models.SlugField(help_text='مثلاً: digikala', max_length=200, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website_screenshot', models.ImageField(blank=True, upload_to='proposals/screenshots/', verbose_name='اسکرین\u200cشات سایت')),
                ('lighthouse_screenshot', models.ImageField(blank=True, upload_to='proposals/lighthouse/', verbose_name='تصویر Lighthouse')),
                ('inspect_screenshot', models.ImageField(blank=True, upload_to='proposals/inspect/', verbose_name='تصویر اینسپکت')),
                ('intro_title', models.CharField(max_length=200, verbose_name='عنوان معرفی')),
                ('intro_text', models.TextField(verbose_name='متن معرفی')),
                ('price', models.CharField(blank=True, help_text='مثلاً: از ۵ میلیون تومان', max_length=100, verbose_name='قیمت پیشنهادی')),
            ],
            options={
                'verbose_name': 'پروپوزال',
                'verbose_name_plural': 'پروپوزال\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seo', 'سئو فنی'), ('speed', 'سرعت'), ('content', 'محتوا'), ('security', 'امنیت'), ('ux', 'تجربه کاربری'), ('other', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('severity', models.CharField(choices=[('critical', 'بحرانی'), ('warning', 'متوسط'), ('info', 'جزئی')], max_length=10, verbose_name='شدت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مشکل')),
                ('description', models.TextField(blank=True, verbose_name='توضیح مشکل')),
                ('solution', models.TextField(blank=True, verbose_name='راه\u200cحل پیشنهادی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.proposal', verbose_name='پروپوزال')),
            ],
            options={
                'verbose_name': 'مشکل',
                'verbose_name_plural': 'مشکلات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('service_type', models.CharField(choices=[('essential', 'ضروری'), ('optional', 'اختیاری')], default='essential', max_length=10, verbose_name='نوع')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='قیمت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.proposal', verbose_name='پروپوزال')),
            ],
            options={
                'verbose_name': 'خدمت پیشنهادی',
                'verbose_name_plural': 'خدمات پیشنهادی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثلاً: امتیاز سرعت فعلی', max_length=100, verbose_name='برچسب')),
                ('current_value', models.CharField(help_text='مثلاً: ۳۲', max_length=50, verbose_name='مقدار فعلی')),
                ('target_value', models.CharField(help_text='مثلاً: ۹۰+', max_length=50, verbose_name='مقدار هدف')),
                ('unit', models.CharField(blank=True, help_text='مثلاً: امتیاز یا ثانیه یا ٪', max_length=20, verbose_name='واحد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.proposal', verbose_name='پروپوزال')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
                'ordering': ['order'],
            },
        ),
    ]
