# Generated by Django 6.0.6 on 2026-06-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برند')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'برند همکار',
                'verbose_name_plural': 'برند های همکار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'CTA سکشن',
                'verbose_name_plural': 'CTA سکشن',
            },
        ),
        migrations.CreateModel(
            name='HeroMarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='متن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'آیتم مارکویی اول هیروسکشن',
                'verbose_name_plural': 'آیتم های مارکویی هیروسکشن',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'هیرو سکشن',
                'verbose_name_plural': 'هیرو سکشن',
            },
        ),
        migrations.CreateModel(
            name='ManifestoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='ساب تایتل ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('highlighted_word', models.CharField(max_length=50, verbose_name='کلمه هایلایت شده')),
                ('paragraph_one', models.TextField(verbose_name='پاراگراف اول')),
                ('paragraph_two', models.TextField(verbose_name='پاراگراف دوم')),
                ('signature_name', models.CharField(max_length=100, verbose_name='نام امضا')),
                ('signature_title', models.CharField(max_length=100, verbose_name='عنوان امضا')),
            ],
            options={
                'verbose_name': 'سکشن برتری های ما',
                'verbose_name_plural': 'سکشن برتری های ما',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سکشن خدمات',
                'verbose_name_plural': 'سکشن خدمات',
            },
        ),
    ]
