# Generated by Django 6.1 on 2026-08-16 13:59

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ')),
                ('cover_image', models.ImageField(upload_to='blog/covers/', verbose_name='تصویر کاور')),
                ('cover_image_alt', models.CharField(max_length=250, verbose_name='متن جایگزین تصویر کاور')),
                ('excerpt', models.TextField(max_length=300, verbose_name='خلاصه مقاله')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوای مقاله')),
                ('reading_time', models.PositiveIntegerField(default=1, editable=False, verbose_name='زمان مطالعه (دقیقه)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا (سئو)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا (سئو)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
