# Generated by Django 6.1 on 2026-08-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role', models.CharField(help_text='مثلاً: استراتژیست سئو · بنیان\u200cگذار', max_length=150, verbose_name='عنوان شغلی')),
                ('avatar', models.ImageField(blank=True, upload_to='blog/authors/', verbose_name='تصویر نویسنده')),
                ('bio', models.TextField(max_length=300, verbose_name='بیوگرافی کوتاه')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='BlogPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: دانش،', max_length=100, verbose_name='عنوان صفحه بلاگ')),
                ('title_highlight', models.CharField(help_text='مثلاً: بی\u200cواسطه.', max_length=100, verbose_name='بخش هایلایت\u200cشده عنوان')),
                ('description', models.TextField(verbose_name='توضیحات صفحه بلاگ')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه بلاگ',
                'verbose_name_plural': 'تنظیمات صفحه بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
