# Generated by Django 6.1 on 2026-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_blogpagesettings_tag_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagesettings',
            name='title_highlight',
        ),
    ]
