# Generated by Django 6.0.6 on 2026-06-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='تصویر اصلی')),
                ('client_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('year', models.CharField(max_length=10, verbose_name='سال')),
                ('service_type', models.CharField(max_length=200, verbose_name='حوزه کاری')),
                ('client_url', models.URLField(blank=True, verbose_name='لینک سایت مشتری')),
                ('challenge', models.TextField(blank=True, verbose_name='چالش ها')),
                ('solution', models.TextField(blank=True, verbose_name='راهکار ها')),
                ('featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی ؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='portfolio.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='مثلا +35%', max_length=50, verbose_name='عدد')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name=' برچسب')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات کوتاه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='portfolio.portfolio', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمار ها',
                'ordering': ['order'],
            },
        ),
    ]
