# Generated by Django 6.0.6 on 2026-06-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliopagesecteion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPageSecteion',
            new_name='PortfolioPageSection',
        ),
    ]
